version: 0.2

env:
  variables:
    RUST_VERSION: "1.76.0"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Entered the install phase on `date`
      - |
        echo Installing Rust $RUST_VERSION
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none --profile minimal
        export PATH="/root/.cargo/bin:$PATH"
        rustup toolchain install $RUST_VERSION
        rustup default $RUST_VERSION
        pip3 install cargo-lambda
    finally:
      - |
        echo Changing all file times to 2010-01-01 00:00:00 \(arbitrary\) to avoid inducing changes in ZIP packages
        find . -not -path '*/.git/*' -exec touch -a -m -t"201001010000.00" {} \;
      - echo Exiting the install phase on `date`
  pre_build:
    on-failure: ABORT
    commands:
      - echo Entered the pre_build phase on `date`
      - |
        RUST_LIB_PATH=./rust/libs
        RUST_LAMBDA_PATH=./rust/lambdas
      - |
        if ! previous_build_rust_version=$(cat previous_build_rust_version 2>/dev/null) || [ "$previous_build_rust_version" != "$RUST_VERSION" ]; then
          echo "Rust version changed $previous_build_rust_version -> $RUST_VERSION, cleaning everything"
          cargo clean
          echo $RUST_VERSION > previous_build_rust_version
        fi
      - |
        echo Cleaning targets cache if necessary
        declare -A PACKAGES_TO_CLEAN
        if ! [ -d rust_target_md5sum ] ; then mkdir rust_target_md5sum ; fi
        echo Selectively clean-up LIB artifacts if code has changed
        for LIB in $(ls $RUST_LIB_PATH) ; do
          echo Control MD5 for $RUST_LIB_PATH/$LIB
          cd $RUST_LIB_PATH/$LIB
          current_md5=$(find . | sort | zip -@ - | md5sum | cut -f1 -d" ")
          cd $CODEBUILD_SRC_DIR
          if ! previous_md5=$(cat rust_target_md5sum/$LIB 2>/dev/null) || [ "$previous_md5" != "$current_md5" ] ; then
            echo previous_md5=$previous_md5 current_md5=$current_md5 =\> Clean lib $LIB and updating md5sum
            PACKAGES_TO_CLEAN+=([$LIB]=1)
            echo $current_md5 > rust_target_md5sum/$LIB
          fi
        done
        echo Selectively clean-up LAMBDA artifacts if code has changed
        for LAMBDA in $(ls $RUST_LAMBDA_PATH) ; do
          echo Control MD5 for $RUST_LAMBDA_PATH/$LAMBDA
          cd $RUST_LAMBDA_PATH/$LAMBDA
          current_md5=$(find . | sort | zip -@ - | md5sum | cut -f1 -d" ")
          cd $CODEBUILD_SRC_DIR
          if ! previous_md5=$(cat rust_target_md5sum/$LAMBDA 2>/dev/null) || [ "$previous_md5" != "$current_md5" ] ; then
            echo previous_md5=$previous_md5 current_md5=$current_md5 => Clean $LAMBDA and updating md5sum
            PACKAGES_TO_CLEAN+=([$LAMBDA]=1)
            echo $current_md5 > rust_target_md5sum/$LAMBDA
          fi
        done
        if [ -f Cargo.lock.old ] ; then
          mv Cargo.lock Cargo.lock.new
          cp Cargo.lock.old Cargo.lock
        fi
        if [ -f Cargo.lock.old ] ; then
          declare -A CURRENT_PACKAGES
          echo Building current packages set...
          for p in $(perl -0pe 's/^.*?(\[\[package\]\]\nname = "(\S+)"\nversion = "(\S+)".*?\n)+$/\2@\3\n/gms' < Cargo.lock.new) ; do
            CURRENT_PACKAGES+=([$p]=1)
          done
          echo Finding all packages that are no longer needed...
          for p in $(perl -0pe 's/^.*?(\[\[package\]\]\nname = "(\S+)"\nversion = "(\S+)".*?\n)+$/\2@\3\n/gms' < Cargo.lock.old) ; do
            if ! [[ ${CURRENT_PACKAGES[$p]} -eq 1 ]]; then
              for ptc in $(cargo tree --prefix none -e no-dev -i --target aarch64-unknown-linux-gnu --package $p | sed -r 's/^(\S+).*$/\1/'); do
                echo "Removing $ptc"
                PACKAGES_TO_CLEAN+=([$ptc]=1)
              done
            fi
          done
        fi
        echo Cleaning ${#PACKAGES_TO_CLEAN[@]} packages...
        for package in ${!PACKAGES_TO_CLEAN[@]}; do
          echo Cleaning $package
          cargo clean --locked --target aarch64-unknown-linux-gnu --release --package $package
        done
        if [ -f Cargo.lock.new ] ; then
          rm -f Cargo.lock
          mv Cargo.lock.new Cargo.lock
        fi
      - |
        echo Updating Cargo.lock.old
        cp Cargo.lock Cargo.lock.old
    finally:
      - echo Exiting the pre_build phase on `date`
  build:
    on-failure: ABORT
    commands:
      - echo Entered the build phase on `date`
      - |
        echo Building release command...
        CMD="cargo lambda build --locked --release --arm64"
        for LAMBDA in $(ls $RUST_LAMBDA_PATH) ; do
          echo Will build $LAMBDA
          CMD="$CMD --package $LAMBDA"
        done
        echo $CMD
        eval $CMD
      - |
        echo Packaging lambdas...
        for LAMBDA in $(ls $RUST_LAMBDA_PATH) ; do
          echo Preping: $LAMBDA
          # Remove all content
          rm -rf $RUST_LAMBDA_PATH/$LAMBDA/*
          # Move the compiled binary into the Lambda folder
          mv ./target/lambda/$LAMBDA/bootstrap $RUST_LAMBDA_PATH/$LAMBDA/bootstrap
        done
    finally:
      - |
        echo Changing all file times to 2010-01-01 00:00:00 \(arbitrary\) to avoid inducing changes in ZIP packages
        find . -not -path '*/.git/*' -exec touch -a -m -t"201001010000.00" {} \;
      - echo Exiting the build phase on `date`
  post_build:
    commands:
      - echo Entered the post_build phase on `date`
      - |
        echo Soft-link lambda folders
        mkdir lambdas
        ORIG_LAMBDA_FOLDER=$CODEBUILD_SRC_DIR/rust/lambdas
        cd lambdas
        for LAMBDA_FOLDER in $(ls $ORIG_LAMBDA_FOLDER) ; do
          echo Soft-link ./lambdas/$LAMBDA_FOLDER to $ORIG_LAMBDA_FOLDER/$LAMBDA_FOLDER
          ln -s $ORIG_LAMBDA_FOLDER/$LAMBDA_FOLDER $LAMBDA_FOLDER
        done
        cd $CODEBUILD_SRC_DIR
      - |
        echo Packaging the demo-template file references...
        mv demo-template.yml demo-template.yml.bak
        aws cloudformation package --template-file demo-template.yml.bak --s3-bucket $ARTIFACT_BUCKET --s3-prefix templates --output-template-file demo-template.yml
    finally:
      - echo Exiting the post_build phase on `date`
artifacts:
  base-directory: .
  files:
    - demo-template.yml
cache:
  paths:
    - target/**/* # Rust workspace target directory
    - rust_target_md5sum/**/* # Where we store md5sum for code
    - Cargo.lock.old # The last seen Cargo.lock
    - previous_build_rust_version # The last seen Rust toolchain version
