[package]
name = "get-cat-ackermann"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
lambda_apigw_utils = { path = "../../libs/lambda_apigw_utils" }
